### ISSUE TITLE
[Epic] Add IBC UI

### ISSUE THREAD

**Issue by webbushka** [provenance-io/explorer-frontend#130]
This is a meta ticket focusing on tickets that add UI for the new IBC endpoints

## Summary

Add IBC list view, detail view and any other views we deem appropriate

## Problem Definition

There are new IBC endpoints and data we want to show 

### XHR handlers
- [ ] Add IBC Redux actions, reducers and hooks

### List view
- [ ] Add list view page #131
- [ ] Integrate list view link into the top nav

### Detail View
- [ ] Create a detail view
- [ ] Show IBC balances
- [ ] Show channel status
____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
