### ISSUE TITLE
[EPIC] Governance

### ISSUE THREAD

**Issue by webbushka** [provenance-io/explorer-frontend#132]
This is a meta ticket focusing on tickets that add UI for the new Governance endpoints

## Summary

Add Proposal list view, detail view and any other views we deem appropriate

## Problem Definition

There are new Governance Proposal endpoints and data we want to show 

### XHR handlers
- [x] Add Governance Redux actions, reducers and hooks #133 

### List view
- [x] Add list view page #134
- [x] Integrate list view link into the top nav #135

### Detail View
- [x] Create a detail view
  - [x] Show proposal info #136
  - [x] Show timing info graph #137
  - [x] List of voters #138
  - [x] List of deposits #139

### Validator details
- [x] list governance txs associated with the operator address #140
- [x] list of votes made by operator account #141
____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned
