### ISSUE TITLE
[EPIC] Various UI improvements

### ISSUE THREAD

**Issue by minxylynx** [provenance-io/explorer-frontend#269]
## Summary

This is a list of various UI improvements identified while going through the UI. 
Can be broken into separate issues if necessary

## Proposal

- [ ] Validator Detail
    - [ ] Make Delegations, Unbondings collapsible (like accounts)
    - [ ] Add totals to Delegations, Unbondings
    - [ ] Gov Txs
        - [ ] link Proposal ID to proposal detail page, center ID?
        - [ ] Change `Amount` to `Deposit`
- [ ] Tx Detail
    - [ ] Move Total Fees to Fee header?
    - [ ] Link addresses/validators/scopes/contracts/proposals as necessary
        - [ ] BE: Think about translating NFT UUID to MetadataAddress format, would allow easier linking for FE
    - [ ] Add Feepayer to Detail
    - [ ] Add full list of signers
- [ ] Asset Detail
    - [ ] BE: Make APIs return faster, if possible
        - Might be a rendering slowdown
    - [ ] Make Asset Holders list 10 records
        - 30 is too long 
    - [ ] Make asset holders/txs collapsible ?
        - Or do the tabby thing we were discussing. Could add the NFT list in there then too
    - [ ] Figure out a better layout for Asset Detail data
    - [ ] Make NFT total a bigger clickable area
        - text to click instead?
- [ ] NFT Detail
    - [ ] Add UUID to the detail header
    - [ ] Make the Responsible Party list formatted better
    - [ ] Make the specs and Record ids (recordspec, record, etc) clickable to open the associated json
        - API is currently available
- [ ] Gov detail
    - [ ] Make the details easily read
        - I know we like the easy json object thing, but the details should really be listed out, not hidden behind clicks
    - [ ] Better layout to the Header stuff
    - [ ] Better layout to the deposit/vote stuff
        - Graphs are good, but maybe tabs for deposits, votes, with votes being first

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
